[workspace]
members = [
    "ports/glutin",
    "ports/libsimpleservo/capi/",
    "ports/libsimpleservo/jniapi/",
    "ports/libmlservo/",
    "tests/unit/*",
]
exclude = [".cargo"]

[profile.release]
opt-level = 3
# Uncomment to profile on Linux:
# debug = true
# lto = false

[patch.crates-io]
# If you need to temporarily test Servo with a local fork of some upstream
# crate, add that here. Use the form:
#
#     <crate> = { path = "/path/to/local/checkout" }
#
# Or for a git dependency:
#
#     [patch."https://github.com/servo/<repository>"]
#     <crate> = { path = "/path/to/local/checkout" }

# Those are here to dedupe winapi since mio is still using winapi 0.2.
mio = { git = "https://github.com/servo/mio.git", branch = "servo" }
iovec = { git = "https://github.com/servo/iovec.git", branch = "servo" }
remove_dir_all = { git = "https://github.com/servo/remove_dir_all", branch = "arm64" }
cmake = { git = "https://github.com/jdm/cmake-rs", branch = "win-arm64" }
offscreen_gl_context = { git = "https://github.com/jdm/rust-offscreen-rendering-context", branch = "win-egl" }

[patch."https://github.com/servo/mozjs"]
mozjs_sys = { git = "https://github.com/jdm/mozjs", branch = "win-arm64" }
